apiVersion: v1
kind: Service
metadata:
  name: admin-gateway
  namespace: billing-admin
spec:
  type: ClusterIP
  selector:
    app: admin-gateway
  ports:
  - port: 8080
    targetPort: 8080
    name: http
---
apiVersion: v1
kind: Service
metadata:
  name: admin-ui
  namespace: billing-admin
spec:
  type: ClusterIP
  selector:
    app: admin-ui
  ports:
  - port: 80
    targetPort: 80
    name: http
